### ISSUE TITLE
Corregir tildes en string

### ISSUE THREAD

**Issue by miguel-bustos** [castsaku/Montblanc#1]
Se deben corregir los tildes en la siguiente línea:

https://github.com/castsaku/Montblanc/blob/bdbe96f936186726609294bec5c92e8889b20fff/Program.cs#L19

**Comment by castsaku** [comment]
Fixed in commit

https://github.com/castsaku/Montblanc/commit/6e9b88beba5c8845137239fa7d27954d14ede935
